### ISSUE TITLE
<a> tag sometimes doesn't close 🤷🏻‍♂️

### ISSUE THREAD

**Issue by sambeevors** [maizzle/maizzle#33]
The following code:
```blade
<a href="{{ $href ?? 'https://www.example.com' }}" class="no-underline">
  <table
    align="{{ $align ?? 'center' }}"
    class="font-light text-{{ isset($inverted) && $inverted ? 'black' : 'white' }} bg-{{ isset($inverted) && $inverted ? 'white' : 'black' }}"
    cellpadding="0"
    cellspacing="0"
    role="presentation"
  >
    <tr>
      <td
        class="uppercase font-light px-26 py-20 font-sans text-{{ isset($inverted) && $inverted ? 'black' : 'white' }} bg-{{ isset($inverted) && $inverted ? 'white' : 'black' }}"
        align="center"
      >
        {!! $text !!}
      </td>
    </tr>
  </table>
</a>
```

Gives the following output (after running `npm run staging`, same happens across all enviroments):
```html
<a href="https://www.example.com/" style="text-decoration: none;">
    <table align="left" cellpadding="0" cellspacing="0" role="presentation" style="font-weight: 300; color: #ffffff;" bgcolor="#000000">
        <tr>
            <td align="center" style="font-family: Helvetica Neue, Helvetica, -apple-system, Segoe UI, sans-serif; font-weight: 300; padding-top: 20px; padding-bottom: 20px; padding-left: 26px; padding-right: 26px; color: #ffffff; text-transform: uppercase;" bgcolor="#000000">
             Hello world
            </td>
        </tr>
    </table>
```

This remains true even if I remove all the attributes from the child elements, as well as remove `{!! $text !!}`. This doesn't happen in a different partial where it's wrapped around an `<img>` tag.

There is a visible gap where the closing tag should be, too.
<img width="174" alt="screenshot 2019-03-07 at 15 51 17" src="https://user-images.githubusercontent.com/13867100/53969527-dd431300-40f0-11e9-9461-4988734ea837.png">

**Comment by sambeevors** [comment]
Side note: This example is in a component as part of a bigger email, but the same is true if I create the following blade file with only this code in:
```blade
<a href="https://example.com" class="no-underline">
  <table
    align="center"
    class="font-light text-black bg-white"
    cellpadding="0"
    cellspacing="0"
    role="presentation"
  >
    <tr>
      <td
        class="uppercase font-light px-26 py-20 font-sans text-black bg-white"
        align="center"
      >
        Hello world
      </td>
    </tr>
  </table>
</a>
```

**Comment by cossssmin** [comment]
Thanks for opening the issue.

I've tested with the `confirm-email` template and you're right, it doesn't work as expected. However, in my case the table is being hoisted out of the anchor tag - so with your example from above, I get this when doing `npm run dev`:

```xml
<a href="https://example.com" class="no-underline">
  </a><table align="center" class="font-light text-black bg-white" cellpadding="0" cellspacing="0" role="presentation">
    <tr>
      <td class="uppercase font-light px-26 py-20 font-sans text-black bg-white" align="center">
        Hello world
      </td>
    </tr>
  </table>
```

I've tested disabling all transformations and it still happens, so I think it might be coming from Jigsaw. Though I'm not sure where from, as both Parsedown and Parsedown Extra handle that syntax fine if you test it online.

Any chance you could put up your repo or invite me there? Would like to test it a bit more before opening an issue for Jigsaw, especially since it looks like in your case the anchor is simply not closed at all. Thanks!

**Comment by cossssmin** [comment]
I suppose some parser uses HTML 4 spec, which doesn't allow tables inside anchor tags. HTML 5 spec does though...

**Comment by sambeevors** [comment]
@cossssmin You should have an invite to collaborate

**Comment by cossssmin** [comment]
Thanks Sam, I'll check it out.

Meanwhile, I tested a Jigsaw site with this and I'm not seeing any issues, which is very weird. Might be that I tested a Jigsaw `1.3` site, while Maizzle is still using `1.2`. 

I've also tested it in the upcoming Maizzle.js, where I use Marked.js for markdown parsing - thought the parser might be the issue. No problems there: as long as `html-minifier` (which is also used here) is set to use HTML5 spec (`html5: true,`), the anchor tag is properly closed.

Will continue to investigate, and let you know. Thanks again!

**Comment by cossssmin** [comment]
Tested with `html5: true,` for `html-minifier`, and it seems to work. I've pushed a commit to your repo, check it out and let me know how it goes.

**Comment by sambeevors** [comment]
That works a treat, thank you!

**Comment by cossssmin** [comment]
Awesome, I'll go ahead and update the framework. Thanks again for reporting!
